### ISSUE TITLE
Modification : traduire retour de l'endPoint pour ajouter les box

### ISSUE THREAD

**Issue by simon-fauconnier** [EPHEC-Enovatech/sensorygarden-api#28]

**Comment by AdrienNini** [comment]
@simon-fauconnier  Peux-tu valider les traductions ? 

- Erreur de sauvegarde: le user-id n'existe pas
- Erreur de sauvegarde: ce capteur existe déjà
- Sauvegarde réussie !
- Erreur de sauvegarde: Le device_id et/ou le checksum ne peuvent être vide
- Erreur de sauvegarde: Le code de vérification est incorrecte

**Comment by AdrienNini** [comment]
Resolved by #29
