### ISSUE TITLE
Ajout endpoint records par jour et par box

### ISSUE THREAD

**Issue by simon-fauconnier** [EPHEC-Enovatech/sensorygarden-api#45]
**Is your feature request related to a problem? Please describe.**
Ce serait sympa pour le graphique 'radar', pour avoir tous les records d'une box par genre de tous les capteurs...

**Describe the solution you'd like**
Genre un endpoint comme "https://api.sensorygarden.be/records/1A4242B00000000/13-11-2018"

**Comment by AdrienNini** [comment]
Je regarde pour te faire ça dès que je peux ;)
